Avoid newer versions of `safe` with old GHCs
This is necessary because newer versions of `safe` use the -W
syntax instead of the -fwarn syntax.

diff --git a/.github/workflows/haskell-ci.yml b/.github/workflows/haskell-ci.yml
--- a/.github/workflows/haskell-ci.yml
+++ b/.github/workflows/haskell-ci.yml
@@ -191,9 +191,9 @@ jobs:
       - name: initial cabal.project for sdist
         run: |
           touch cabal.project
-          echo "packages: $GITHUB_WORKSPACE/source/units-defs" >> cabal.project
           echo "packages: $GITHUB_WORKSPACE/source/units" >> cabal.project
           echo "packages: $GITHUB_WORKSPACE/source/units-test" >> cabal.project
+          echo "packages: $GITHUB_WORKSPACE/source/units-defs" >> cabal.project
           cat cabal.project
       - name: sdist
         run: |
@@ -205,25 +205,27 @@ jobs:
           find sdist -maxdepth 1 -type f -name '*.tar.gz' -exec tar -C $GITHUB_WORKSPACE/unpacked -xzvf {} \;
       - name: generate cabal.project
         run: |
-          PKGDIR_units_defs="$(find "$GITHUB_WORKSPACE/unpacked" -maxdepth 1 -type d -regex '.*/units-defs-[0-9.]*')"
-          echo "PKGDIR_units_defs=${PKGDIR_units_defs}" >> "$GITHUB_ENV"
           PKGDIR_units="$(find "$GITHUB_WORKSPACE/unpacked" -maxdepth 1 -type d -regex '.*/units-[0-9.]*')"
           echo "PKGDIR_units=${PKGDIR_units}" >> "$GITHUB_ENV"
           PKGDIR_units_test="$(find "$GITHUB_WORKSPACE/unpacked" -maxdepth 1 -type d -regex '.*/units-test-[0-9.]*')"
           echo "PKGDIR_units_test=${PKGDIR_units_test}" >> "$GITHUB_ENV"
+          PKGDIR_units_defs="$(find "$GITHUB_WORKSPACE/unpacked" -maxdepth 1 -type d -regex '.*/units-defs-[0-9.]*')"
+          echo "PKGDIR_units_defs=${PKGDIR_units_defs}" >> "$GITHUB_ENV"
           rm -f cabal.project cabal.project.local
           touch cabal.project
           touch cabal.project.local
-          echo "packages: ${PKGDIR_units_defs}" >> cabal.project
           echo "packages: ${PKGDIR_units}" >> cabal.project
           echo "packages: ${PKGDIR_units_test}" >> cabal.project
-          if [ $((HCNUMVER >= 80200)) -ne 0 ] ; then echo "package units-defs" >> cabal.project ; fi
-          if [ $((HCNUMVER >= 80200)) -ne 0 ] ; then echo "    ghc-options: -Werror=missing-methods" >> cabal.project ; fi
+          echo "packages: ${PKGDIR_units_defs}" >> cabal.project
           if [ $((HCNUMVER >= 80200)) -ne 0 ] ; then echo "package units" >> cabal.project ; fi
           if [ $((HCNUMVER >= 80200)) -ne 0 ] ; then echo "    ghc-options: -Werror=missing-methods" >> cabal.project ; fi
           if [ $((HCNUMVER >= 80200)) -ne 0 ] ; then echo "package units-test" >> cabal.project ; fi
           if [ $((HCNUMVER >= 80200)) -ne 0 ] ; then echo "    ghc-options: -Werror=missing-methods" >> cabal.project ; fi
+          if [ $((HCNUMVER >= 80200)) -ne 0 ] ; then echo "package units-defs" >> cabal.project ; fi
+          if [ $((HCNUMVER >= 80200)) -ne 0 ] ; then echo "    ghc-options: -Werror=missing-methods" >> cabal.project ; fi
           cat >> cabal.project <<EOF
+          if ! impl ( ghc >= 8.0 )
+            constraints: safe < 0.3.18
           EOF
           $HCPKG list --simple-output --names-only | perl -ne 'for (split /\s+/) { print "constraints: $_ installed\n" unless /^(units|units-defs|units-test)$/; }' >> cabal.project.local
           cat cabal.project
@@ -253,11 +255,11 @@ jobs:
           $CABAL v2-test $ARG_COMPILER $ARG_TESTS $ARG_BENCH all --test-show-details=direct
       - name: cabal check
         run: |
-          cd ${PKGDIR_units_defs} || false
-          ${CABAL} -vnormal check
           cd ${PKGDIR_units} || false
           ${CABAL} -vnormal check
           cd ${PKGDIR_units_test} || false
+          ${CABAL} -vnormal check
+          cd ${PKGDIR_units_defs} || false
           ${CABAL} -vnormal check
       - name: haddock
         run: |
